# Generated by Django 5.0.6 on 2024-10-20 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tejapp', '0005_teacher_imglink'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=100)),
                ('imglink', models.CharField(default='/static/blackprog.jpg', max_length=50)),
            ],
        ),
    ]
