# Generated by Django 5.0.6 on 2024-10-20 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tejapp', '0006_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='imglink',
            field=models.CharField(default='/static/blank.png', max_length=50),
        ),
    ]
