# Generated by Django 5.0.6 on 2024-10-20 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tejapp', '0007_alter_course_imglink'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(editable='False', max_length=50)),
                ('email', models.CharField(default=' ', editable='False', max_length=50)),
                ('phone', models.CharField(editable='False', max_length=20)),
                ('desc', models.TextField(editable='False', max_length=200)),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
    ]
