# Generated by Django 5.0.6 on 2024-10-20 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tejapp', '0008_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('short', models.TextField(max_length=100)),
                ('big', models.TextField(max_length=100)),
                ('imglink', models.CharField(default='/static/blank.png', max_length=50)),
                ('link', models.CharField(default='/static/blank.png', max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='contact',
            name='desc',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
