# Generated by Django 5.0.6 on 2024-10-20 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tejapp', '0009_moment_alter_contact_desc_alter_contact_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moment',
            name='big',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='moment',
            name='short',
            field=models.TextField(max_length=500),
        ),
    ]
