# Generated by Django 5.0.6 on 2024-10-20 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tejapp', '0010_alter_moment_big_alter_moment_short'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moment',
            name='imglink',
            field=models.CharField(default='/static/blank.png', max_length=500),
        ),
        migrations.AlterField(
            model_name='moment',
            name='link',
            field=models.CharField(default='/static/blank.png', max_length=500),
        ),
    ]
