# Generated by Django 5.0.6 on 2024-10-20 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tejapp', '0011_alter_moment_imglink_alter_moment_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='moment',
            name='Uniqueid',
            field=models.CharField(default='teacher', max_length=10),
            preserve_default=False,
        ),
    ]
