# Generated by Django 5.0.6 on 2024-10-20 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tejapp', '0013_rename_link_moment_linkforvideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moment',
            name='linkforvideo',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
