# Generated by Django 5.0.6 on 2024-10-20 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tejapp', '0014_alter_moment_linkforvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='moment',
            name='linkformultiplephotos',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='moment',
            name='linkforvideo',
            field=models.CharField(default='', max_length=500),
        ),
    ]
