# Generated by Django 5.0.6 on 2024-10-20 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tejapp', '0015_moment_linkformultiplephotos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moment',
            name='linkformultiplephotos',
            field=models.CharField(default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='moment',
            name='linkforvideo',
            field=models.CharField(default='', max_length=500, null=True),
        ),
    ]
